import { normalizePath, TFolder, type App, type PluginManifest, type TAbstractFile } from "obsidian";
import type { Prefix, SimpleColoredFolderSettings, StyleSettingValue } from "./interfaces";
import type SimpleColoredFolder from "./main";
import { convertStyleSettings, convertToCSS, generateName, themes } from "./template";
import { minifyCss, removeExtraNewLine } from "./utils";
import dedent from "dedent";

export class ColorCompiler {
	plugin: SimpleColoredFolder;
	settings: SimpleColoredFolderSettings;
	style: HTMLStyleElement | null = null;
	app: App;
	snippetPath: string = "generated.colored-folder.css";
	manifest: PluginManifest
	constructor(plugin: SimpleColoredFolder) {
		this.plugin = plugin;
		this.settings = plugin.settings;
		this.app = plugin.app;
		this.style = plugin.style;
		this.snippetPath = plugin.snippetPath;
		this.manifest = plugin.manifest;
	}

	styleSettingsHeader() {
		return dedent(`
		/* @settings
		name: ${this.manifest.name}
		id: ${this.manifest.id}
		settings:
      -
          id: FolderRadius
          type: variable-number-slider
          title: ${i18next.t("common.radius")}
          default: 5
          min: 0
          max: 20
          step: 1
          format: px
      -
          id: space-between
          type: variable-number-slider
          default: 0.3
          max: 5
          step: 0.1
          min: 0
          format: em
          title: ${i18next.t("common.space")}
      -`);
	}

	createStyles(folders: TFolder[]) {
		let darkTheme = `.theme-dark {`;
		let lightTheme = `.theme-light {`;
		let css = "";
		let stylesSettings = this.styleSettingsHeader();
		for (const folder of folders) {
			const folderName = folder.name;
			const vn = generateName(this.settings.prefix, folderName, "--");
			darkTheme += themes(vn);
			lightTheme += themes(vn);
			css += convertToCSS(folderName, this.settings.prefix, this.settings.customTemplate);
			stylesSettings += convertStyleSettings(
				folderName,
				this.settings.prefix,
				this.settings.customStyleSettings
			);
		}
		darkTheme += "}";
		lightTheme += "}";
		stylesSettings = `${stylesSettings.replace(/-+$/, "").trimEnd()}\n*/`;
		return `\n${removeExtraNewLine(stylesSettings)}\n${minifyCss(darkTheme)}\n${minifyCss(lightTheme)}\n${minifyCss(css)}`;
	}

	async injectToBody(content: string) {
		if (await this.app.vault.adapter.exists(this.snippetPath))
			this.app.customCss.setCssEnabledStatus("generated.colored-folder", false);
		this.style = document.createElement("style");
		this.style.id = "simple-colored-folder";
		this.style.setAttribute("type", "text/css");
		this.style.textContent = content;
		document.head.appendChild(this.style);

	}

	async injectToSnippets(content: string) {
		const obsidianDir = normalizePath(`${this.app.vault.configDir}/snippets`);
		if (!(await this.app.vault.adapter.exists(obsidianDir))) {
			//create
			console.log("Creating snippets directory");
			await this.app.vault.adapter.mkdir(obsidianDir);
		}
		const rules = `/* This file is generated by Simple Colored Folder. Do not edit it manually\n${content}`;
		await this.app.vault.adapter.write(this.snippetPath, rules);
		//enable the snippet
		this.app.customCss.setCssEnabledStatus("generated.colored-folder", true);
	}

	async injectStyles(reload = true) {
		const folders = this.app.vault
			.getAllFolders()
			.filter(
				(folder: TFolder) => folder.parent && folder.parent === this.app.vault.getRoot()
			);
		this.style?.detach();
		const style = this.createStyles(folders);
		if (this.settings.exportToCSS) await this.injectToSnippets(style);
		else await this.injectToBody(style);
		if (reload) this.reload();
	}

	async renameCss(newPath: TAbstractFile, oldPath: string) {
		const styleSettingPlugin = this.app.plugins.getPlugin("obsidian-style-settings");
		if (!styleSettingPlugin) return;
		if (newPath instanceof TFolder && newPath.parent === this.app.vault.getRoot()) {
			const settings = (await styleSettingPlugin.loadData()) as Record<
				string,
				StyleSettingValue
			>;
			const oldNames = generateName(this.settings.prefix, oldPath);
			const generateKeys = (prefix: Prefix) => {
				return {
					bg: {
						light: `${this.manifest.id}@@${prefix.bg}@@light`,
						dark: `${this.manifest.id}@@${prefix.bg}@@dark`,
					},
					color: {
						light: `${this.manifest.id}@@${prefix.color}@@light`,
						dark: `${this.manifest.id}@@${prefix.color}@@dark`,
					},
				};
			};

			const oldKeys = generateKeys(oldNames);
			const newKeys = generateKeys(generateName(this.settings.prefix, newPath.name));

			const styleSettingsValues: Record<string, StyleSettingValue | undefined> = {
				[newKeys.bg.light]: settings?.[oldKeys.bg.light],
				[newKeys.bg.dark]: settings?.[oldKeys.bg.dark],
				[newKeys.color.light]: settings?.[oldKeys.color.light],
				[newKeys.color.dark]: settings?.[oldKeys.color.dark],
			};
			//if every key is undefined => no need to re-apply the theming, just return
			if (
				!Object.values(styleSettingsValues).some(
					(value) => value !== undefined && value !== ""
				)
			)
				return this.injectStyles();
			await this.injectStyles();
			//@ts-ignore
			styleSettingPlugin.settingsManager.setSettings(styleSettingsValues);

		}
	}

	async injectToRoot(file: TAbstractFile) {
		if (file instanceof TFolder && file.parent === this.app.vault.getRoot())
			await this.injectStyles();
	}

	reload() {
		this.app.workspace.trigger("css-change");
	}
}