import {
	type App,
	normalizePath,
	type PluginManifest,
	type TAbstractFile,
	TFolder,
} from "obsidian";
import type { FolderTreeItem } from "obsidian-typings";
import { ColorGetter } from "./getter";
import {
	type Prefix,
	type SimpleColoredFolderSettings,
	STYLE_SPLIT,
	type StyleSettingValue,
} from "./interfaces";
import type SimpleColoredFolder from "./main";
import { createStyles, generateName } from "./utils/template";

export class ColorInjector {
	plugin: SimpleColoredFolder;
	settings: SimpleColoredFolderSettings;
	style: HTMLStyleElement | null = null;
	app: App;
	snippetPath: string = "generated.colored-folder.css";
	manifest: PluginManifest;
	getter: ColorGetter;
	constructor(plugin: SimpleColoredFolder) {
		this.plugin = plugin;
		this.settings = plugin.settings;
		this.app = plugin.app;
		this.style = plugin.style;
		this.snippetPath = plugin.snippetPath;
		this.manifest = plugin.manifest;
		this.getter = new ColorGetter(this.app);
	}

	async toBody(content: string) {
		if (await this.app.vault.adapter.exists(this.snippetPath)) {
			this.app.customCss.setCssEnabledStatus("generated.colored-folder", false);
		}

		const domStyle = document.head.querySelector<HTMLStyleElement>(
			"#simple-colored-folder"
		);

		this.style ??= domStyle;
		if (this.style) {
			//remove the old style
			this.style.detach();
			this.style.remove();
			this.style = null;
		}

		this.style = document.createElement("style");
		this.style.id = "simple-colored-folder";
		this.style.setAttribute("type", "text/css");
		this.style.textContent = content;
		document.head.appendChild(this.style);
	}

	async toSnippets(content: string) {
		const snippetsDir = normalizePath(`${this.app.vault.configDir}/snippets`);
		if (!(await this.app.vault.adapter.exists(snippetsDir))) {
			//create
			console.warn("Creating snippets directory");
			await this.app.vault.adapter.mkdir(snippetsDir);
		}
		let rules = `/* This file is generated by Simple Colored Folder. Do not edit it manually */`;
		if (this.settings.includeStyleInExport) rules += await this.pluginStyles();

		rules += `\n${content}\n`;
		await this.app.vault.adapter.write(this.snippetPath, rules);
		//enable the snippet
		this.app.customCss.setCssEnabledStatus("generated.colored-folder", true);
	}

	private async pluginStyles() {
		const pluginDir = normalizePath(
			`${this.app.vault.configDir}/plugins/${this.manifest.id}`
		);
		const stylesPath = normalizePath(`${pluginDir}/styles.css`);
		if (await this.app.vault.adapter.exists(stylesPath)) {
			const styles = (await this.app.vault.adapter.read(stylesPath))
				.split(STYLE_SPLIT)
				.filter((x) => x.length > 0)[0];
			return `\n\n/* ---- */\n${styles}`;
		} else console.error("The plugin folder doesn't exists.");

		return "";
	}

	/**
	 * Inject the data-path into the .tree-item.nav-folder
	 */
	async dataPath(
		folders: TFolder[] = this.getter.getFolderAtRoot(),
		fileExplorer = this.getter.getFileExplorerView()
	) {
		if (!fileExplorer) return;

		const fileItems = fileExplorer.fileItems;
		//get the FileTreeItem corresponding to the folder
		if (!fileItems) {
			console.warn("File items not found in file explorer");
			return;
		}
		for (const folder of folders) {
			const folderItem = this.getter.getFileItems(folder, fileItems);
			if (!folderItem) {
				console.warn(`Folder item not found for folder: ${folder.path}`);
				continue;
			}
			await this.getter.injectDataPathFromFolder(folder, folderItem as FolderTreeItem);
		}
	}

	async styles(reload = true, folders: TFolder[] = this.getter.getFolderAtRoot()) {
		this.style?.detach();
		const exportToCSS = this.settings.exportToCSS;
		const style = createStyles(folders, this.manifest, this.settings, !exportToCSS);
		if (exportToCSS) await this.toSnippets(style);
		else await this.toBody(style);
		if (reload) this.reload();
	}

	async renameCss(newPath: TAbstractFile, oldPath: string) {
		const styleSettingPlugin = this.app.plugins.getPlugin("obsidian-style-settings");
		if (!styleSettingPlugin) return;
		if (newPath instanceof TFolder && newPath.parent === this.app.vault.getRoot()) {
			const settings = (await styleSettingPlugin.loadData()) as Record<
				string,
				StyleSettingValue
			>;
			const oldNames = generateName(this.settings.prefix, oldPath);
			const generateKeys = (prefix: Prefix) => {
				return {
					bg: {
						light: `${this.manifest.id}@@${prefix.bg}@@light`,
						dark: `${this.manifest.id}@@${prefix.bg}@@dark`,
					},
					color: {
						light: `${this.manifest.id}@@${prefix.color}@@light`,
						dark: `${this.manifest.id}@@${prefix.color}@@dark`,
					},
				};
			};

			const oldKeys = generateKeys(oldNames);
			const newKeys = generateKeys(generateName(this.settings.prefix, newPath.name));

			const styleSettingsValues: Record<string, StyleSettingValue | undefined> = {
				[newKeys.bg.light]: settings?.[oldKeys.bg.light],
				[newKeys.bg.dark]: settings?.[oldKeys.bg.dark],
				[newKeys.color.light]: settings?.[oldKeys.color.light],
				[newKeys.color.dark]: settings?.[oldKeys.color.dark],
			};
			//if every key is undefined => no need to re-apply the theming, just return
			if (
				!Object.values(styleSettingsValues).some(
					(value) => value !== undefined && value !== ""
				)
			)
				return this.styles();
			await this.styles();
			//@ts-ignore
			styleSettingPlugin.settingsManager.setSettings(styleSettingsValues);
		}
	}

	async toRoot(file: TAbstractFile) {
		if (file instanceof TFolder && file.parent === this.app.vault.getRoot())
			await this.styles();
	}

	reload() {
		this.app.workspace.trigger("css-change");
	}
}
